# Generated by Django 5.2.3 on 2025-08-04 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('indie', 'Indie'), ('mpb', 'MPB'), ('eletronica', 'Eletrônica'), ('jazz', 'Jazz'), ('classica', 'Clássica'), ('sertanejo', 'Sertanejo'), ('rap', 'Rap'), ('funk', 'Funk'), ('samba', 'Samba'), ('forro', 'Forró'), ('bossa_nova', 'Bossa Nova'), ('reggae', 'Reggae'), ('blues', 'Blues'), ('gospel', 'Gospel'), ('country', 'Country'), ('soul', 'Soul'), ('hip_hop', 'Hip Hop'), ('metal', 'Metal'), ('punk', 'Punk'), ('swing', 'Swing'), ('latino', 'Latino'), ('kpop', 'K-Pop'), ('eletronica_brasileira', 'Eletrônica Brasileira'), ('trap', 'Trap'), ('brega', 'Brega'), ('sertanejo_universitario', 'Sertanejo Universitário'), ('pagode', 'Pagode'), ('axé', 'Axé')], max_length=100)),
                ('data_lancamento', models.DateField(auto_now_add=True)),
                ('audio', models.FileField(upload_to='musicas/')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capa_musica/')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='bemteouvi.musico')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=100)),
                ('foto_evento', models.ImageField(blank=True, null=True, upload_to='foto_evento/')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='bemteouvi.musico')),
            ],
        ),
        migrations.CreateModel(
            name='EstatisticaMensalMusico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('minutos_ouvidos', models.IntegerField(default=0)),
                ('total_reproducoes', models.IntegerField(default=0)),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemteouvi.musico')),
            ],
        ),
        migrations.CreateModel(
            name='Ouvinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroOuvido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=100)),
                ('segundos_ouvidos', models.IntegerField(default=0)),
                ('ouvinte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemteouvi.ouvinte')),
            ],
        ),
        migrations.CreateModel(
            name='EstatisticaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('minutos_ouvidos', models.IntegerField(default=0)),
                ('ouvinte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemteouvi.ouvinte')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='playlists/')),
                ('musicas', models.ManyToManyField(related_name='playlists', to='bemteouvi.musica')),
                ('musico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='bemteouvi.musico')),
                ('ouvinte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='bemteouvi.ouvinte')),
            ],
        ),
        migrations.CreateModel(
            name='Reproducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('duracao_segundos', models.IntegerField(default=0)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemteouvi.musica')),
                ('ouvinte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemteouvi.ouvinte')),
            ],
        ),
    ]
