# Generated by Django 5.2.5 on 2025-08-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bemteouvi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musica",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="musicas/"),
        ),
    ]
