# Generated by Django 5.2.7 on 2025-10-27 16:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('capa_do_album', models.ImageField(upload_to='capas_de_album')),
                ('data_de_lancamento', models.DateField()),
                ('genero_musical', models.CharField(choices=[('jazz', 'Jazz'), ('rock', 'Rock'), ('pop', 'Pop'), ('classica', 'Clássica'), ('hip_hop', 'Hip Hop'), ('eletronica', 'Eletrônica'), ('samba', 'Samba'), ('mpb', 'MPB'), ('forro', 'Forró'), ('blues', 'Blues'), ('reggae', 'Reggae'), ('bossa_nova', 'Bossa Nova')])),
                ('numero_de_musicas', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('lance_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lance_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('perfil', models.CharField(choices=[('musico', 'Músico'), ('ouvinte', 'Ouvinte')], max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lances_usuario', to=settings.AUTH_USER_MODEL)),
                ('leilao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lances_leilao', to='api.leilao')),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autores', models.CharField(max_length=200)),
                ('autor_melodia', models.CharField(max_length=200)),
                ('letra', models.TextField()),
                ('autor_letra', models.CharField(max_length=200)),
                ('data_criacao', models.DateField()),
                ('arquivo_audio', models.FileField(upload_to='musicas')),
                ('genero', models.CharField(choices=[('jazz', 'Jazz'), ('rock', 'Rock'), ('pop', 'Pop'), ('classica', 'Clássica'), ('hip_hop', 'Hip Hop'), ('eletronica', 'Eletrônica'), ('samba', 'Samba'), ('mpb', 'MPB'), ('forro', 'Forró'), ('blues', 'Blues'), ('reggae', 'Reggae'), ('bossa_nova', 'Bossa Nova')])),
                ('duracao', models.DurationField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='api.album')),
            ],
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_usuário', to=settings.AUTH_USER_MODEL)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_musica', to='api.musica')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_usuario', to=settings.AUTH_USER_MODEL)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_musica', to='api.musica')),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_artistico', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_de_perfil')),
                ('redes_sociais', models.URLField(blank=True, null=True)),
                ('generos_musicais', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='leilao',
            name='musico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leiloes_musico', to='api.musico'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('imagem_do_evento', models.ImageField(upload_to='imagens_de_evento')),
                ('data_do_evento', models.DateTimeField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_musico', to='api.musico')),
            ],
        ),
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_count', models.IntegerField(default=0)),
                ('curtidas_count', models.IntegerField(default=0)),
                ('comentarios_count', models.IntegerField(default=0)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas_musica', to='api.musica')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas_musico', to='api.musico')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='musicos',
            field=models.ManyToManyField(to='api.musico'),
        ),
        migrations.CreateModel(
            name='Ouvinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_de_perfil')),
                ('generos_favoritos', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('musicas', models.ManyToManyField(related_name='playlists_musica', to='api.musica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
