# Generated by Django 5.2.7 on 2025-10-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_popular_dados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='numero_de_musicas',
        ),
        migrations.RemoveField(
            model_name='estatistica',
            name='musico',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='musico',
            name='generos_musicais',
        ),
        migrations.RemoveField(
            model_name='ouvinte',
            name='generos_favoritos',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='autor_letra',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='autor_melodia',
        ),
        migrations.AddField(
            model_name='musica',
            name='autor_letra',
            field=models.ManyToManyField(related_name='autor_da_letra', to='api.musico'),
        ),
        migrations.AddField(
            model_name='musica',
            name='autor_melodia',
            field=models.ManyToManyField(related_name='autor_da_melodia', to='api.musico'),
        ),
    ]
