# Generated by Django 5.2.7 on 2025-12-02 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_album_numero_de_musicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatistica',
            name='musica',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas_musica', to='api.musica'),
        ),
    ]
