# Generated by Django 5.2.7 on 2025-12-02 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_estatistica_musica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musico',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='musico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ouvinte',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ouvinte', to=settings.AUTH_USER_MODEL),
        ),
    ]
