# Generated by Django 5.2.7 on 2025-12-09 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_musico_user_alter_ouvinte_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerCountUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("play_count", models.IntegerField(default=0)),
                ("ultima_reproducao", models.DateTimeField(auto_now=True)),
                (
                    "musica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_count_musica",
                        to="api.musica",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_count_usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "musica")},
            },
        ),
    ]
