# Generated by Django 5.2.7 on 2025-12-11 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_playercountusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genero_musical',
            field=models.CharField(choices=[('jazz', 'Jazz'), ('rock', 'Rock'), ('pop', 'Pop'), ('classica', 'Clássica'), ('hip_hop', 'Hip Hop'), ('eletronica', 'Eletrônica'), ('samba', 'Samba'), ('mpb', 'MPB'), ('forro', 'Forró'), ('blues', 'Blues'), ('reggae', 'Reggae'), ('bossa_nova', 'Bossa Nova')], max_length=20),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='musica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.musica'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curtida',
            name='musica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='api.musica'),
        ),
        migrations.AlterField(
            model_name='curtida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estatistica',
            name='musica',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='api.musica'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='musico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.musico'),
        ),
        migrations.AlterField(
            model_name='lance',
            name='leilao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lances', to='api.leilao'),
        ),
        migrations.AlterField(
            model_name='lance',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='musico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leiloes', to='api.musico'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='autor_letra',
            field=models.ManyToManyField(related_name='letras', to='api.musico'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='autor_melodia',
            field=models.ManyToManyField(related_name='melodias', to='api.musico'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='genero',
            field=models.CharField(choices=[('jazz', 'Jazz'), ('rock', 'Rock'), ('pop', 'Pop'), ('classica', 'Clássica'), ('hip_hop', 'Hip Hop'), ('eletronica', 'Eletrônica'), ('samba', 'Samba'), ('mpb', 'MPB'), ('forro', 'Forró'), ('blues', 'Blues'), ('reggae', 'Reggae'), ('bossa_nova', 'Bossa Nova')], max_length=20),
        ),
        migrations.AlterField(
            model_name='playercountusuario',
            name='musica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.musica'),
        ),
        migrations.AlterField(
            model_name='playercountusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='musicas',
            field=models.ManyToManyField(related_name='playlists', to='api.musica'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
